'''
    @Author: Ankitha B L
    @Date: 27-11-2024
    @Last Modified by: Ankitha B L
    @Last Modified time: 28-11-2024
    @Title : python program for numpy library
'''

### Q1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array

In [1]:
import numpy as np
import logger

In [ ]:
log = logger.logger_init('Q1')


def list_to_array(lst_ele):
    """ 
    Description :
        This function is used to convert a list of numeric value into a one-dimensional NumPy 
    Parameters :
        lst_ele =  list elements
    Return :
        It returns numpy array elements
    """
    arr = np.array(lst_ele)
    return arr


def main():
    lst = [1,2,3,4,7,9]
    np_arr  = list_to_array(lst)
    print(f"The array elements are :{np_arr} and array type is :{type(np_arr)}")


if __name__ =="__main__":
    main()

The array elements are :[1 2 3 4 7 9] and array type is :<class 'numpy.ndarray'>


### Q2. Create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
log = logger.logger_init('Q2')


def generate_matrix():
    """ 
    Description :
        This function is used to Create a 3x3 matrix with values ranging from 2 to 10
        
    Return :
        It returns 3d array with values ranging from 2 to 10
    """
    z = np.arange(2,11)
    arr = z.reshape(3,3)
    return arr


def main():
    res_arr = generate_matrix()
    print(f"The resultant matrix is :\n {res_arr}")


if __name__ =="__main__":
    main()


The resultant matrix is :
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Q3.Write a Python program to create a null vector of size 10 and update sixth value to 10

In [ ]:
log = logger.logger_init('Q3')


def generate_null_vector():
    """ 
    Description :
        This function is used to create a null vector of size 10 and update sixth value to 11
        
    Return :
        It returns array that contains null vector of size 10 and update sixth value to 11
    """
    arr = np.zeros(10)
    arr[6] = 11
    return arr

def main():
    print(f"Updated 6th value :{generate_null_vector()}")


if __name__ =="__main__":
    main()


Updated 6th value :[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


### Q4. Write a Python program to reverse an array (first element becomes last)

In [5]:
log = logger.logger_init('Q4')


def reverse_arr(arr_ele):
    """ 
    Description :
        This function is used to reverse an array 
    Parameters :
        arr_ele = Numpy array elements
    Return :
        It returns reversed array 
    """
    return reversed(arr_ele)


def main():
    arr = np.arange(12,38)
    print(f"Original Array :{arr}")
    res_arr = reverse_arr(arr)
    res = [item for item in res_arr]
    print(f"The reversed array :\n{res}")


if __name__ =="__main__":
    main()

Original Array :[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
The reversed array :
[37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12]


### Q5.Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [6]:
log = logger.logger_init('Q5')


def generate_2d_arr():
    """ 
    Description :
        This function is used to create a 2d array with 1 on the border and 0 inside
        
    Return :
        It returns 2d array with 1 on the border and 0 inside
    """
    arr = np.ones((5,5))
    z = np.zeros((3,3))
    arr[1:4,1:4] = z
    return arr


def main():
    res_arr = generate_2d_arr()
    print(f"The resultent  2D array is :\n {res_arr}")


if __name__ =="__main__":
    main()

The resultent  2D array is :
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Q6. Write a Python program to add a border (filled with 0's) around an existing array 

In [7]:
log = logger.logger_init('Q6')


def generate_desired_matrix():
    """ 
    Description :
        This function is used to add a border (filled with 0's) around an existing array
        
    Return :
        It returns  border matrix filled with 0's around an existing array
    """
    arr = np.zeros((5,5))
    z = np.ones((3,3))
    arr[1:4,1:4] = z
    return arr


def main():
    res_arr = generate_desired_matrix()
    print(f"The resultant matrix is :\n {res_arr}")


if __name__ =="__main__":
    main()

The resultant matrix is :
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### Q7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [8]:
log = logger.logger_init('Q7')


def generate_checkerboard_pattern():
    """ 
    Description :
        This function is used to create a 8x8 matrix and fill it with a checkerboard pattern
        
    Return :
        It returns 8x8 matrix and fill it with a checkerboard pattern
    """
    arr = np.zeros((8,8),dtype='int32')
    arr[1::2,::2] = 1
    arr[::2,1::2] = 1
    return arr

def main():
    print(f"Generated checkboard pattern :\n{generate_checkerboard_pattern()}")

if __name__ =="__main__":
    main()

Generated checkboard pattern :
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Q8. Write a Python program to convert a list and tuple into arrays

In [10]:
log = logger.logger_init('Q8')


def list_tuple_to_array(lst_ele,tup_ele):
    """ 
    Description :
        This function is used to convert a list and tuple into arrays
    Parameters :
        lst_ele = list elements
        tup_ele = tuple elements
    Return :
        It returns array 
    """
    arr = np.asarray(lst_ele)
    arr1 = np.asarray(tup_ele)
    return arr,arr1


def main():
    lst = [1,2,3,4,5,6,7,8]
    tup_ele = ((8,4,6),(1,2,3))
    print(f"List and Tuple into array elements are :\n{list_tuple_to_array(lst,tup_ele)}")
    
    
if __name__ =="__main__":
    main()

List and Tuple into array elements are :
(array([1, 2, 3, 4, 5, 6, 7, 8]), array([[8, 4, 6],
       [1, 2, 3]]))


### Q9. Write a Python program to append values to the end of an array

In [ ]:
log = logger.logger_init('Q9')


def append_values(x):
    """ 
    Description :
        This function is used to append values to the end of an array
    Parameters :
        x = Numpy array elements
    Return :
        It returns array after appending values 
    """
    arr = np.append(x,[40,50,60,70,80,90])
    return arr


def main():
    arr = np.array([10, 20, 30])
    print(f"The original array :{arr}")
    print(f"The array after appending values :{append_values(arr)}")
    
    
if __name__ =="__main__":
    main()

The original array :[10 20 30]
The array after appending values :[10 20 30 40 50 60 70 80 90]


### Q10. Write a Python program to find the real and imaginary parts of an array of complex numbers

In [ ]:
log = logger.logger_init('Q10')


def find_real_img(arr):
    """ 
    Description :
        This function is used to find the real and imaginary parts of an array of complex numbers
    Parameters :
        arr = Numpy array elements
    Return :
        It returns real and imaginary parts of an array of complex numbers
    """
    real =  np.real(arr)
    print(f"Real part of the array :\n{real}")
    img = np.imag(arr)
    print(f"Imaginary part of the array :\n{img}")
    

def main():
    arr =  [ 1.00000000+0.j, 0.70710678+0.70710678j]
    find_real_img(arr)
    
    
if __name__ == "__main__":
    main()

Real part of the array :
[1.         0.70710678]
Imaginary part of the array :
[0.         0.70710678]


### Q11. Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements

In [13]:
log = logger.logger_init('Q11')


def arr_attributes(arr_ele):
    """ 
    Description :
        This function is used to find the number of elements of an array, length of one
        array element in bytes and total bytes consumed by the elements 
    Parameters :
        arr_ele = Numpy array elements
    Return :
        It returns number of elements of an array, length of one array element in bytes and total bytes consumed by the elements 
    """
    size_arr = arr_ele.size
    item_size = arr_ele.itemsize
    num_bytes = arr_ele.nbytes
    return size_arr,item_size,num_bytes


def main():
    arr = np.array([[1,2,3],[4,5,6]])
    arr_size,size_item,bytes_num = arr_attributes(arr)
    print(f"Size of the array: {arr_size}")
    print(f"Length of one array element in bytes: {size_item}")
    print(f"Total bytes consumed by the elements of the array: {bytes_num}")
    
    
if __name__ == "__main__":
    main()

Size of the array: 6
Length of one array element in bytes: 4
Total bytes consumed by the elements of the array: 24


### Q12. Write a Python program to find common values between two arrays

In [ ]:
log = logger.logger_init('Q12')


def arr_attributes(arr1,arr2):
    """ 
    Description :
        This function is used to find common values between two arrays 
    Parameters :
        arr1 = First array elements
        arr2 = Second array elements
    Return :
        It returns the common elements
    """
    res_ele = np.intersect1d(arr1,arr2)
    return res_ele


def main():
    arr1 = np.array([[0, 10, 20], [40, 60, 80]])
    arr2 = np.array([10, 30, 40])
    res = arr_attributes(arr1,arr2)
    print(f"Common elements are :{res}")
    
    
if __name__ == "__main__":
    main()

Common elements are :[10 40]


### Q13. Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2

In [ ]:
log = logger.logger_init('Q13')


def set_difference(arr1,arr2):
    """ 
    Description :
        This function is used to find the set difference of two arrays 
    Parameters :
        arr1 = First array elements
        arr2 = Second array elements
    Return :
        It returns set difference of two arrays
    """
    res_arr = np.setdiff1d(arr1,arr2)
    return res_arr

    
def main():
    arr1 = np.array([0,10,20,40,60,80])
    arr2 = np.array([10, 30, 40, 50, 70, 90])
    print(f"Set difference between two arrays: {set_difference(arr1,arr2)}")
    
    
if __name__ == "__main__":
    main()

Set difference between two arrays: [ 0 20 60 80]


### Q14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays

In [ ]:
log = logger.logger_init('Q14')


def set_exclusive_or(arr1,arr2):
    """ 
    Description :
        This function is used to find the set exclusive-or of two arrays. 
    Parameters :
        arr1 = First array elements
        arr2 = Second array elements
    Return :
        It returns set exclusive-or of two arrays
    """
    arr_unique = np.setxor1d(arr1,arr2)
    return arr_unique
    
    
def main():
    arr1 = np.array([ 0,10,20,40,60,80])
    arr2 = np.array([10, 30, 40, 50, 70, 90])
    print(f" Unique values that are in only one (not both) of the input arrays: {set_exclusive_or(arr1,arr2)}")
    
    
if __name__ == "__main__":
    main()

 Unique values that are in only one (not both) of the input arrays: [ 0 20 30 50 60 70 80 90]


### Q15. Write a Python program compare two arrays using numpy

In [20]:
log = logger.logger_init('Q15')


def compare_arrs(arr1,arr2):
    """ 
    Description :
        This function is used to compare two arrays using numpy
    Parameters :
        arr1 = First array elements
        arr2 = Second array elements
    Return :
        It returns compared two arrays elements
    """
    res1 = np.greater(arr1,arr2)
    res2 = np.greater_equal(arr1,arr2)
    res3 = np.less(arr1,arr2)
    res4 = np.less_equal(arr1,arr2)
    return res1,res2,res3,res4


def main():
    arr1 = np.array( [1,2])
    arr2 = np.array( [4,5])
    res  = compare_arrs(arr1,arr2)
    for item in res:
        print(item)
    
    
if __name__ == "__main__":
    main()

[False False]
[False False]
[ True  True]
[ True  True]


### Q16. Write a Python program to save a NumPy array to a text file 

In [21]:
log = logger.logger_init('Q16')


def save_to_file(arr):
    """ 
    Description :
        This function is used to save a NumPy array to a text file 
    Parameters :
        arr = Numpy array elements
    """
    np.savetxt('file.out',arr,delimiter=',')

    
def main():
    arr = np.array([1,2,3,4,5])
    save_to_file(arr)
    
    
if __name__ == "__main__":
    main()

### Q17. Write a Python program to create a contiguous flattened array

In [22]:
log = logger.logger_init('Q17')


def flatten_arr(arr):
    """ 
    Description :
        This function is used to create a contiguous flattened array 
    Parameters :
        arr = Numpy array elements
    Return :
        It returns flattened array
    """
    return np.ravel(arr)


def main():
    arr = np.array([[10,20,30],[20,40,50]])
    print(f"New flattened array: \n{flatten_arr(arr)}")
    
    
if __name__ == "__main__":
    main()

New flattened array: 
[10 20 30 20 40 50]
