'''
    @Author: Ankitha B L
    @Date: 27-11-2024
    @Last Modified by: Ankitha B L
    @Last Modified time: 27-11-2024
    @Title : python program for numpy library
'''

### Q1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array

In [1]:
import numpy as np
import logger

In [ ]:
log = logger.logger_init('Q1')


def list_to_array(lst_ele):
    """ 
    Description :
        This function is used to convert a list of numeric value into a one-dimensional NumPy 
    Parameters :
        lst_ele =  list elements
    Return :
        It returns numpy array elements
    """
    arr = np.array(lst_ele)
    return arr


def main():
    lst = [1,2,3,4,7,9]
    np_arr  = list_to_array(lst)
    print(f"The array elements are :{np_arr} and array type is :{type(np_arr)}")


if __name__ =="__main__":
    main()

The array elements are :[1 2 3 4 7 9] and array type is :<class 'numpy.ndarray'>


### Q2. Create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
log = logger.logger_init('Q2')


def generate_matrix():
    """ 
    Description :
        This function is used to Create a 3x3 matrix with values ranging from 2 to 10
        
    Return :
        It returns 3d array with values ranging from 2 to 10
    """
    z = np.arange(2,11)
    arr = z.reshape(3,3)
    return arr


def main():
    res_arr = generate_matrix()
    print(f"The resultant matrix is :\n {res_arr}")


if __name__ =="__main__":
    main()


The resultant matrix is :
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Q3.Write a Python program to create a null vector of size 10 and update sixth value to 10

In [ ]:
log = logger.logger_init('Q3')


def generate_null_vector():
    """ 
    Description :
        This function is used to create a null vector of size 10 and update sixth value to 11
        
    Return :
        It returns array that contains null vector of size 10 and update sixth value to 11
    """
    arr = np.zeros(10)
    arr[6] = 11
    return arr

def main():
    print(f"Updated 6th value :{generate_null_vector()}")


if __name__ =="__main__":
    main()


Updated 6th value :[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


### Q4. Write a Python program to reverse an array (first element becomes last)

In [5]:
log = logger.logger_init('Q4')


def reverse_arr(arr_ele):
    """ 
    Description :
        This function is used to reverse an array 
    Parameters :
        arr_ele = Numpy array elements
    Return :
        It returns reversed array 
    """
    return reversed(arr_ele)


def main():
    arr = np.arange(12,38)
    print(f"Original Array :{arr}")
    res_arr = reverse_arr(arr)
    res = [item for item in res_arr]
    print(f"The reversed array :\n{res}")


if __name__ =="__main__":
    main()

Original Array :[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
The reversed array :
[37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12]


### Q5.Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [6]:
log = logger.logger_init('Q5')


def generate_2d_arr():
    """ 
    Description :
        This function is used to create a 2d array with 1 on the border and 0 inside
        
    Return :
        It returns 2d array with 1 on the border and 0 inside
    """
    arr = np.ones((5,5))
    z = np.zeros((3,3))
    arr[1:4,1:4] = z
    return arr


def main():
    res_arr = generate_2d_arr()
    print(f"The resultent  2D array is :\n {res_arr}")


if __name__ =="__main__":
    main()

The resultent  2D array is :
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Q6. Write a Python program to add a border (filled with 0's) around an existing array 

In [7]:
log = logger.logger_init('Q6')


def generate_desired_matrix():
    """ 
    Description :
        This function is used to add a border (filled with 0's) around an existing array
        
    Return :
        It returns  border matrix filled with 0's around an existing array
    """
    arr = np.zeros((5,5))
    z = np.ones((3,3))
    arr[1:4,1:4] = z
    return arr


def main():
    res_arr = generate_desired_matrix()
    print(f"The resultant matrix is :\n {res_arr}")


if __name__ =="__main__":
    main()

The resultant matrix is :
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### Q7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [8]:
log = logger.logger_init('Q7')


def generate_checkerboard_pattern():
    """ 
    Description :
        This function is used to create a 8x8 matrix and fill it with a checkerboard pattern
        
    Return :
        It returns 8x8 matrix and fill it with a checkerboard pattern
    """
    arr = np.zeros((8,8),dtype='int32')
    arr[1::2,::2] = 1
    arr[::2,1::2] = 1
    return arr

def main():
    print(f"Generated checkboard pattern :\n{generate_checkerboard_pattern()}")

if __name__ =="__main__":
    main()

Generated checkboard pattern :
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Q8. Write a Python program to convert a list and tuple into arrays

In [10]:
log = logger.logger_init('Q8')


def list_tuple_to_array(lst_ele,tup_ele):
    """ 
    Description :
        This function is used to convert a list and tuple into arrays
    Parameters :
        lst_ele = list elements
        tup_ele = tuple elements
    Return :
        It returns array 
    """
    arr = np.asarray(lst_ele)
    arr1 = np.asarray(tup_ele)
    return arr,arr1


def main():
    lst = [1,2,3,4,5,6,7,8]
    tup_ele = ((8,4,6),(1,2,3))
    print(f"List and Tuple into array elements are :\n{list_tuple_to_array(lst,tup_ele)}")
    
    
if __name__ =="__main__":
    main()

List and Tuple into array elements are :
(array([1, 2, 3, 4, 5, 6, 7, 8]), array([[8, 4, 6],
       [1, 2, 3]]))
