'''
    @Author: Ankitha B L
    @Date: 27-11-2024
    @Last Modified by: Ankitha B L
    @Last Modified time: 27-11-2024
    @Title : python program for numpy library
'''

### Q1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array

In [1]:
import numpy as np
import logger

In [ ]:
log = logger.logger_init('Q1')


def list_to_array(lst_ele):
    """ 
    Description :
        This function is used to convert a list of numeric value into a one-dimensional NumPy 
    Parameters :
        lst_ele =  list elements
    Return :
        It returns numpy array elements
    """
    arr = np.array(lst_ele)
    return arr


def main():
    lst = [1,2,3,4,7,9]
    np_arr  = list_to_array(lst)
    print(f"The array elements are :{np_arr} and array type is :{type(np_arr)}")


if __name__ =="__main__":
    main()

The array elements are :[1 2 3 4 7 9] and array type is :<class 'numpy.ndarray'>


### Q2. Create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
log = logger.logger_init('Q2')


def generate_matrix():
    """ 
    Description :
        This function is used to Create a 3x3 matrix with values ranging from 2 to 10
        
    Return :
        It returns 3d array with values ranging from 2 to 10
    """
    z = np.arange(2,11)
    arr = z.reshape(3,3)
    return arr


def main():
    res_arr = generate_matrix()
    print(f"The resultant matrix is :\n {res_arr}")


if __name__ =="__main__":
    main()


The resultant matrix is :
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Q3.Write a Python program to create a null vector of size 10 and update sixth value to 10

In [4]:
log = logger.logger_init('Q2')


def generate_null_vector():
    """ 
    Description :
        This function is used to create a null vector of size 10 and update sixth value to 11
        
    Return :
        It returns array that contains null vector of size 10 and update sixth value to 11
    """
    arr = np.zeros(10)
    arr[6] = 11
    return arr

def main():
    print(f"Updated 6th value :{generate_null_vector()}")


if __name__ =="__main__":
    main()


Updated 6th value :[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
